#!/bin/bash
cd `dirname $0`/../

scripts/build

echo Pushing :latest tag
docker push jicksta/sync-evernote:latest

if [[ "$#" == 1 ]]; then
  TAG=$1
  docker tag jicksta/sync-evernote:latest jicksta/sync-evernote:$TAG
  echo Pushing :$TAG tag
  docker push jicksta/sync-evernote:$TAG
  git tag -f $TAG
  git push --tags
fi
