#!/usr/bin/env ruby
require_relative '../src/sync_evernote'

sync = SyncEvernote.new

total_chunks = sync.max_remote_chunk
local_chunks = sync.local_chunks.count

percent_downloaded = (local_chunks.to_f / total_chunks.to_f) * 100

puts
puts "The sync is %.2f%% complete. ( %d / %d )" % [percent_downloaded, local_chunks, total_chunks]
puts
