#!/usr/bin/env ruby
require_relative '../src/sync_evernote'

sync = SyncEvernote.new

abort "Sync hasn't even begun!" if sync.saved_usns.none?

furthest_chunk = sync.max_local_usn
total_chunks   = sync.max_remote_usn

percent_downloaded = 1.0 * furthest_chunk / total_chunks * 100

puts
puts "The sync is %.2f%% complete. ( %d / %d )" % [percent_downloaded, furthest_chunk, total_chunks]
puts


sync.max
